### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by donatj** [turgittin/lunaroomnet#1]
Hey, there's a link going around Twitter about PHP projects with major security problems that are easy to find using github search.  

Your `album/03-portraits/admin.php` comes up.  That may be there because you got hacked if you didn't put it there on purpose.  You should probably check this / remove this.

You probably want to fix this ASAP as your domain lunaroom.net is in your git repo name and makes it an easy target.

https://github.com/search?q=eval($_POST&ref=searchresults&type=Code&utf8=✓

**Comment by erdidoqan** [comment]
Hey, thank you for your interest. and then what can we do for this issue, i think some virus in this (album/03-portraits/plugin.php) is it a virus or nothing else..

**Comment by donatj** [comment]
Probably just want to delete it ;)

**Comment by erdidoqan** [comment]
probably also other files have, isnt it?

**Comment by donatj** [comment]
could just search through your code for eval

**Comment by erdidoqan** [comment]
ou thank a lot :)
